# this allows to test plugin very quickly
#   run `./build-panel.sh` first
#   then run `docker-compose up`
---
version: "3.9"
services:
  grafana:
    image: grafana/grafana:8.1.1
    volumes:
      - ./dist:/var/lib/grafana/plugins/pyroscope-panel
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=pyroscope-panel
      - GF_INSTALL_PLUGINS=pyroscope-datasource
    ports:
      - 3000:3000

  pyroscope:
    image: "pyroscope/pyroscope:latest"
    ports:
      - 4040:4040
    command:
      - server
    environment:
      - PYROSCOPE_LOG_LEVEL=info
