global:
  enabled: true
  jsonOutput: false
  reportAll: true

analyzers:
  version:
    enabled: false
  # there's a false positive happening
  # TODO: update after https://github.com/grafana/plugin-validator/issues/105 is fixed
  trackingscripts:
    enabled: false
