name: 'package-plugin'
inputs:
  grafana-token:
    description: 'Token to be used when signing (from grafana.com)'
    required: true
outputs:
  archive:
    description: "The plugin zip file"
    value: ${{ steps.metadata.outputs.archive }}
  checksum:
    description: "The checksum of the zip file"
    value: ${{ steps.metadata.outputs.archive-checksum }}
runs:
  using: "composite"
  steps:
  - run: yarn sign
    shell: bash
    env:
      GRAFANA_API_KEY: ${{ inputs.grafana-token }}
  - name: Get plugin metadata
    id: metadata
    shell: bash
    run: |
      sudo apt-get install jq

      export GRAFANA_PLUGIN_ID=$(cat dist/plugin.json | jq -r .id)
      export GRAFANA_PLUGIN_VERSION=$(cat dist/plugin.json | jq -r .info.version)
      export GRAFANA_PLUGIN_TYPE=$(cat dist/plugin.json | jq -r .type)
      export GRAFANA_PLUGIN_ARTIFACT=${GRAFANA_PLUGIN_ID}-${GRAFANA_PLUGIN_VERSION}.zip
      export GRAFANA_PLUGIN_ARTIFACT_CHECKSUM=${GRAFANA_PLUGIN_ARTIFACT}.md5

      echo "::set-output name=plugin-id::${GRAFANA_PLUGIN_ID}"
      echo "::set-output name=plugin-version::${GRAFANA_PLUGIN_VERSION}"
      echo "::set-output name=plugin-type::${GRAFANA_PLUGIN_TYPE}"
      echo "::set-output name=archive::${GRAFANA_PLUGIN_ARTIFACT}"
      echo "::set-output name=archive-checksum::${GRAFANA_PLUGIN_ARTIFACT_CHECKSUM}"

      echo ::set-output name=github-tag::${GITHUB_REF#refs/*/}

  - name: Package plugin
    id: packag-
    shell: bash
    run: |
      mv dist ${{ steps.metadata.outputs.plugin-id }}
      zip ${{ steps.metadata.outputs.archive }} ${{ steps.metadata.outputs.plugin-id }} -r
      md5sum ${{ steps.metadata.outputs.archive }} > ${{ steps.metadata.outputs.archive-checksum }}
      echo "::set-output name=checksum::$(cat ./${{ steps.metadata.outputs.archive-checksum }} | cut -d' ' -f1)"
