name: 'lint-plugin'
inputs:
  enable-version-analyzer:
    description: 'Whether to analyze the version or not'
    required: true
  file:
    description: 'the plugin file (.zip)'
    required: true
runs:
  using: "composite"
  steps:
  - name: prepare config file
    shell: bash -euxo pipefail {0}
    run: envsubst < lint2.config.yaml > lint2.config.yaml
  - name: Lint plugin
    shell: bash
    run: |
      export PATH="$(go env GOPATH)/bin/:$PATH"
      git clone https://github.com/grafana/plugin-validator
      pushd ./plugin-validator/pkg/cmd/plugincheck2
      git log -1
      go install
      popd

      plugincheck2 -strict -config lint2.config.yaml -sourceCodeUri=file://./ ${{ inputs.file }}
    env:
      ENABLE_VERSION_ANALYZER: ${{ inputs.enable-version-analyzer }}
      DEBUG: 1

