name: 'lint-plugin'
inputs:
  enable-version-analyzer:
    description: 'Whether to analyze the version or not'
    required: true
  file:
    description: 'the plugin file (.zip)'
    required: true
runs:
  using: "composite"
  steps:
  - name: Render Deployment YAML
    uses: nowactions/envsubst@v1
    with:
      input: ./lint.config.yaml.tmpl
      output: ./lint.config.yaml
    env:
      ENABLE_VERSION_ANALYZER: ${{ inputs.enable-version-analyzer }}
  - name: Lint plugin
    shell: bash
    run: |
      export PATH="$(go env GOPATH)/bin/:$PATH"
      git clone https://github.com/grafana/plugin-validator
      pushd ./plugin-validator/pkg/cmd/plugincheck2
      go install
      popd

      plugincheck2 -strict -config lint.config.yaml -sourceCodeUri=file://./ ${{ inputs.file }}
    env:
      DEBUG: 1

