name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "14.17"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
 
      - name: Cache yarn cache
        uses: actions/cache@v2
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
 
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

      - name: Build plugin
        run: yarn build
        env:
          PYROSCOPE_PANEL_VERSION: test


      # We reuse the same tests from the other repo, after all, why not?
      # TODO: run other tests that are valid here
      # eg: checking README etc
      - name: Run grafana server
        run: docker-compose -f pyroscope/grafana-plugin/panel/docker-compose.yml up -d
      - name: Run tests
        run: yarn --cwd pyroscope cy:panel:ci
        env:
          CYPRESS_VIDEO: true
          CYPRESS_COMPARE_SNAPSHOTS: true
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-screenshots
          path: pyroscope/cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: pyroscope/cypress/videos
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-snapshots
          # TODO: scope to only store screenshots that refer to grafana
          path: pyroscope/cypress/snapshots
