name: Lint

env:
  CYPRESS_CACHE_FOLDER: cypress/cache

on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node/
      - run: yarn sign
      - uses: ./.github/actions/package-plugin/
        id: package-plugin
        with:
          grafana-token: ${{ secrets.GRAFANA_API_KEY }}
      - uses: ./.github/actions/lint-plugin/
        with:
          file: ${{ steps.package-plugin.outputs.archive }}
          enable-version-analyzer: false
      - uses: pCYSl5EDgo/cat@master
        id: hello
        with:
          path: lint.config.yaml
      - name: Lint plugin
        run: |
          export PATH="$(go env GOPATH)/bin/:$PATH"
          pushd ./plugin-validator/pkg/cmd/plugincheck2
          go build .
          popd
          ./plugin-validator/pkg/cmd/plugincheck2/plugincheck2 -strict -config lint.config.yaml -sourceCodeUri=file://./ ${{ steps.package-plugin.outputs.archive }}
        env:
          ENABLE_VERSION_ANALYZER: ${{ inputs.enable-version-analyzer }}
          DEBUG: 1
