name: Lint

env:
  CYPRESS_CACHE_FOLDER: cypress/cache

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Lint plugin
      run: |
        envsubst < lint.config.yaml > lint.config.yaml
        cat lint.config.yaml
        export PATH="$(go env GOPATH)/bin/:$PATH"
        git clone https://github.com/grafana/plugin-validator
        pushd ./plugin-validator/pkg/cmd/plugincheck2
        git log -1
        go install
        popd

        plugincheck2 -strict -config lint.config.yaml -sourceCodeUri=file://./ ${{ inputs.file }}
    env:
      ENABLE_VERSION_ANALYZER: ${{ inputs.enable-version-analyzer }}
      DEBUG: 1

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node/
      - run: yarn sign
      - uses: ./.github/actions/package-plugin/
        id: package-plugin
        with:
          grafana-token: ${{ secrets.GRAFANA_API_KEY }}
      - uses: ./.github/actions/lint-plugin/
        with:
          file: ${{ steps.package-plugin.outputs.archive }}
          enable-version-analyzer: false
