name: Lint

env:
  CYPRESS_CACHE_FOLDER: cypress/cache

on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node/
      - run: yarn sign
      - uses: ./.github/actions/package-plugin/
        id: package-plugin
        with:
          grafana-token: ${{ secrets.GRAFANA_API_KEY }}
      - uses: ./.github/actions/lint-plugin/
        with:
          file: ${{ steps.package-plugin.outputs.archive }}
          enable-version-analyzer: false
