name: Cypress

env:
  CYPRESS_CACHE_FOLDER: cypress/cache

on:
  pull_request:
    branches:
      - main
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node/
      - name: Cache Cypress Binary
        id: cache-cypress-binary
        uses: actions/cache@v2
        with:
          path: cypress/cache
          key: cypress-binary-${{ hashFiles('yarn.lock') }}
      - run: yarn cypress install
      - name: Run grafana server
        run: docker-compose -f docker-compose.yml up -d
      - name: Run tests
        run: yarn cy:ci
        env:
          CYPRESS_VIDEO: true
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-screenshots
          path: pyroscope/cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: pyroscope/cypress/videos
