name: Release

on:
  release:
    # https://stackoverflow.com/a/61066906
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node/
      - run: yarn sign
      - uses: ./.github/actions/package-plugin/
        id: package-plugin
        with:
          grafana-token: ${{ secrets.GRAFANA_API_KEY }}
      - uses: ./.github/actions/lint-plugin/
        with:
          file: ${{ steps.package-plugin.outputs.archive }}
          enable-version-analyzer: true

      - name: Add plugin to release
        id: upload-plugin-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.package-plugin.outputs.archive }}
          asset_name: ${{ steps.package-plugin.outputs.archive }}
          asset_content_type: application/zip

      - name: Add checksum to release
        id: upload-checksum-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.package-plugin.outputs.checksum }}
          asset_name: ${{ steps.package-plugin.outputs.checksum }}
          asset_content_type: text/plain

      - name: Publish to Grafana.com
        run: |
          echo "A release has been created for your plugin. Please review and publish it."
          echo "To publish a new version, follow https://github.com/grafana/grafana-plugin-repository#maintain-your-plugin"
